CREATE TABLE SURVDEMO.POLICY
(
    POLICY_ID             CHAR(12)       NOT NULL,
    INSURED_ID            CHAR(10)       NOT NULL,
    PRODUCT_CODE          CHAR(6)        NOT NULL,
    BASE_MONTHLY_BENEFIT  DECIMAL(11,2)  NOT NULL,
    FAMILY_MAX_PCT        DECIMAL(5,2)   NOT NULL WITH DEFAULT 100.00,
    STATUS                CHAR(1)        NOT NULL WITH DEFAULT 'A',
    EFFECTIVE_DATE        DATE           NOT NULL,
    TERMINATION_DATE      DATE,
    CREATED_TS            TIMESTAMP      NOT NULL WITH DEFAULT,
    UPDATED_TS            TIMESTAMP      NOT NULL WITH DEFAULT,
    PRIMARY KEY (POLICY_ID),
    CONSTRAINT SURVDEMO.CK_POLICY_STATUS
        CHECK (STATUS IN ('A', 'L', 'T')),
    CONSTRAINT SURVDEMO.CK_FAMILY_MAX
        CHECK (FAMILY_MAX_PCT > 0 AND FAMILY_MAX_PCT <= 100.00)
);

CREATE TABLE SURVDEMO.SURVIVOR_CLAIM
(
    CLAIM_ID          CHAR(12)       NOT NULL,
    POLICY_ID         CHAR(12)       NOT NULL,
    DATE_OF_DEATH     DATE           NOT NULL,
    CLAIM_STATUS      CHAR(1)        NOT NULL,
    APPROVED_DATE     DATE,
    VERSION_NO        INTEGER        NOT NULL WITH DEFAULT 1,
    UPDATED_TS        TIMESTAMP      NOT NULL WITH DEFAULT,
    PRIMARY KEY (CLAIM_ID),
    CONSTRAINT SURVDEMO.FK_CLAIM_POLICY
        FOREIGN KEY (POLICY_ID)
        REFERENCES SURVDEMO.POLICY (POLICY_ID),
    CONSTRAINT SURVDEMO.CK_CLAIM_STATUS
        CHECK (CLAIM_STATUS IN ('P', 'A', 'D', 'C'))
);

CREATE TABLE SURVDEMO.BENEFICIARY
(
    BENEFICIARY_ID    CHAR(10)       NOT NULL,
    BENEFICIARY_NAME  VARCHAR(60)    NOT NULL,
    DATE_OF_BIRTH     DATE           NOT NULL,
    RELATIONSHIP      CHAR(3)        NOT NULL,
    STATUS            CHAR(1)        NOT NULL WITH DEFAULT 'A',
    CREATED_TS        TIMESTAMP      NOT NULL WITH DEFAULT,
    UPDATED_TS        TIMESTAMP      NOT NULL WITH DEFAULT,
    PRIMARY KEY (BENEFICIARY_ID),
    CONSTRAINT SURVDEMO.CK_BENE_RELATION
        CHECK (RELATIONSHIP IN ('SPS', 'CHD', 'DEP')),
    CONSTRAINT SURVDEMO.CK_BENE_STATUS
        CHECK (STATUS IN ('A', 'I', 'D'))
);

CREATE TABLE SURVDEMO.SURVIVOR_ENTITLEMENT
(
    CLAIM_ID            CHAR(12)       NOT NULL,
    BENEFICIARY_ID      CHAR(10)       NOT NULL,
    BENEFIT_PCT         DECIMAL(5,2)   NOT NULL,
    OTHER_INCOME_OFFSET DECIMAL(11,2)  NOT NULL WITH DEFAULT 0,
    START_DATE          DATE           NOT NULL,
    END_DATE            DATE,
    STATUS              CHAR(1)        NOT NULL,
    MONTHLY_AMOUNT      DECIMAL(11,2)  NOT NULL WITH DEFAULT 0,
    TOTAL_PAID          DECIMAL(13,2)  NOT NULL WITH DEFAULT 0,
    VERSION_NO          INTEGER        NOT NULL WITH DEFAULT 1,
    UPDATED_TS          TIMESTAMP      NOT NULL WITH DEFAULT,
    PRIMARY KEY (CLAIM_ID, BENEFICIARY_ID),
    CONSTRAINT SURVDEMO.FK_ENT_CLAIM
        FOREIGN KEY (CLAIM_ID)
        REFERENCES SURVDEMO.SURVIVOR_CLAIM (CLAIM_ID),
    CONSTRAINT SURVDEMO.FK_ENT_BENE
        FOREIGN KEY (BENEFICIARY_ID)
        REFERENCES SURVDEMO.BENEFICIARY (BENEFICIARY_ID),
    CONSTRAINT SURVDEMO.CK_ENT_PCT
        CHECK (BENEFIT_PCT > 0 AND BENEFIT_PCT <= 100.00),
    CONSTRAINT SURVDEMO.CK_ENT_OFFSET
        CHECK (OTHER_INCOME_OFFSET >= 0),
    CONSTRAINT SURVDEMO.CK_ENT_STATUS
        CHECK (STATUS IN ('A', 'S', 'E', 'C'))
);

CREATE TABLE SURVDEMO.CALC_RUN
(
    RUN_ID             CHAR(12)       NOT NULL,
    CALC_DATE          DATE           NOT NULL,
    BENEFIT_MONTH      DATE           NOT NULL,
    PAYMENT_COUNT      INTEGER        NOT NULL WITH DEFAULT 0,
    PAYMENT_TOTAL      DECIMAL(13,2)  NOT NULL WITH DEFAULT 0,
    EXCEPTION_COUNT    INTEGER        NOT NULL WITH DEFAULT 0,
    STATUS             CHAR(1)        NOT NULL,
    CREATED_TS         TIMESTAMP      NOT NULL WITH DEFAULT,
    COMPLETED_TS       TIMESTAMP,
    PRIMARY KEY (RUN_ID),
    CONSTRAINT SURVDEMO.CK_RUN_STATUS
        CHECK (STATUS IN ('R', 'C', 'F'))
);

CREATE TABLE SURVDEMO.BENEFIT_PAYMENT
(
    PAYMENT_ID         CHAR(16)       NOT NULL,
    RUN_ID             CHAR(12)       NOT NULL,
    CLAIM_ID           CHAR(12)       NOT NULL,
    BENEFICIARY_ID     CHAR(10)       NOT NULL,
    BENEFIT_MONTH      DATE           NOT NULL,
    GROSS_AMOUNT       DECIMAL(11,2)  NOT NULL,
    OFFSET_AMOUNT      DECIMAL(11,2)  NOT NULL,
    NET_AMOUNT         DECIMAL(11,2)  NOT NULL,
    STATUS             CHAR(1)        NOT NULL,
    CREATED_TS         TIMESTAMP      NOT NULL WITH DEFAULT,
    PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT SURVDEMO.FK_PAY_RUN
        FOREIGN KEY (RUN_ID)
        REFERENCES SURVDEMO.CALC_RUN (RUN_ID),
    CONSTRAINT SURVDEMO.FK_PAY_ENT
        FOREIGN KEY (CLAIM_ID, BENEFICIARY_ID)
        REFERENCES SURVDEMO.SURVIVOR_ENTITLEMENT
                   (CLAIM_ID, BENEFICIARY_ID),
    CONSTRAINT SURVDEMO.CK_PAY_STATUS
        CHECK (STATUS IN ('R', 'C', 'V'))
);

CREATE UNIQUE INDEX SURVDEMO.UX_PAY_PERIOD
    ON SURVDEMO.BENEFIT_PAYMENT
       (CLAIM_ID, BENEFICIARY_ID, BENEFIT_MONTH);

CREATE TABLE SURVDEMO.CALC_EXCEPTION
(
    EXCEPTION_ID       BIGINT GENERATED ALWAYS AS IDENTITY,
    RUN_ID             CHAR(12)       NOT NULL,
    CLAIM_ID           CHAR(12),
    BENEFICIARY_ID     CHAR(10),
    EXCEPTION_CODE     CHAR(2)        NOT NULL,
    EXPECTED_AMOUNT    DECIMAL(11,2),
    ACTUAL_AMOUNT      DECIMAL(11,2),
    STATUS             CHAR(1)        NOT NULL WITH DEFAULT 'O',
    CREATED_TS         TIMESTAMP      NOT NULL WITH DEFAULT,
    PRIMARY KEY (EXCEPTION_ID),
    CONSTRAINT SURVDEMO.FK_EX_RUN
        FOREIGN KEY (RUN_ID)
        REFERENCES SURVDEMO.CALC_RUN (RUN_ID),
    CONSTRAINT SURVDEMO.CK_EX_STATUS
        CHECK (STATUS IN ('O', 'R', 'C'))
);

CREATE INDEX SURVDEMO.IX_CLAIM_POLICY_STATUS
    ON SURVDEMO.SURVIVOR_CLAIM (POLICY_ID, CLAIM_STATUS, CLAIM_ID);

CREATE INDEX SURVDEMO.IX_ENT_CALC
    ON SURVDEMO.SURVIVOR_ENTITLEMENT
       (STATUS, START_DATE, END_DATE, CLAIM_ID, BENEFICIARY_ID);

CREATE INDEX SURVDEMO.IX_EXCEPTION_RUN
    ON SURVDEMO.CALC_EXCEPTION (RUN_ID, EXCEPTION_CODE);
