CREATE TABLE TRSYDEMO.COMPANY_LIMIT
(
    COMPANY_CODE       CHAR(4)        NOT NULL,
    CURRENCY           CHAR(3)        NOT NULL,
    DAILY_LIMIT        DECIMAL(15,2)  NOT NULL,
    STATUS             CHAR(1)        NOT NULL WITH DEFAULT 'A',
    PRIMARY KEY (COMPANY_CODE, CURRENCY)
);

CREATE TABLE TRSYDEMO.PAYMENT_INSTRUCTION
(
    PAYMENT_ID         CHAR(12)       NOT NULL,
    COMPANY_CODE       CHAR(4)        NOT NULL,
    BENEFICIARY_ID     CHAR(10)       NOT NULL,
    PAYMENT_METHOD     CHAR(3)        NOT NULL,
    CURRENCY           CHAR(3)        NOT NULL,
    AMOUNT             DECIMAL(13,2)  NOT NULL,
    EFFECTIVE_DATE     DATE           NOT NULL,
    DEBIT_ACCOUNT      CHAR(12)       NOT NULL,
    BENEFICIARY_NAME   VARCHAR(60)    NOT NULL,
    BANK_ROUTING       CHAR(9)        NOT NULL,
    BANK_ACCOUNT       CHAR(17)       NOT NULL,
    BANK_COUNTRY       CHAR(2)        NOT NULL,
    END_TO_END_ID      CHAR(20)       NOT NULL,
    STATUS             CHAR(1)        NOT NULL,
    BANK_TRACE         CHAR(15),
    REJECT_REASON      CHAR(4),
    VERSION_NO         INTEGER        NOT NULL WITH DEFAULT 1,
    UPDATED_TS         TIMESTAMP      NOT NULL WITH DEFAULT,
    PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT TRSYDEMO.CK_PAY_METHOD
        CHECK (PAYMENT_METHOD IN ('ACH', 'WIR')),
    CONSTRAINT TRSYDEMO.CK_PAY_STATUS
        CHECK (STATUS IN ('A', 'S', 'T', 'R', 'E', 'C'))
);

CREATE UNIQUE INDEX TRSYDEMO.UX_PAY_END_TO_END
    ON TRSYDEMO.PAYMENT_INSTRUCTION
       (COMPANY_CODE, END_TO_END_ID);

CREATE TABLE TRSYDEMO.DISBURSEMENT_BATCH
(
    BATCH_ID           CHAR(12)       NOT NULL,
    VALUE_DATE         DATE           NOT NULL,
    CURRENCY           CHAR(3)        NOT NULL,
    PAYMENT_COUNT      INTEGER        NOT NULL,
    PAYMENT_TOTAL      DECIMAL(15,2)  NOT NULL,
    STATUS             CHAR(1)        NOT NULL,
    FILE_NAME          VARCHAR(128)   NOT NULL,
    CREATED_TS         TIMESTAMP      NOT NULL WITH DEFAULT,
    PRIMARY KEY (BATCH_ID)
);

CREATE TABLE TRSYDEMO.DISBURSEMENT_ITEM
(
    BATCH_ID           CHAR(12)       NOT NULL,
    PAYMENT_ID         CHAR(12)       NOT NULL,
    SEQUENCE_NO        INTEGER        NOT NULL,
    AMOUNT             DECIMAL(13,2)  NOT NULL,
    PRIMARY KEY (BATCH_ID, PAYMENT_ID),
    CONSTRAINT TRSYDEMO.FK_ITEM_BATCH
        FOREIGN KEY (BATCH_ID)
        REFERENCES TRSYDEMO.DISBURSEMENT_BATCH (BATCH_ID),
    CONSTRAINT TRSYDEMO.FK_ITEM_PAYMENT
        FOREIGN KEY (PAYMENT_ID)
        REFERENCES TRSYDEMO.PAYMENT_INSTRUCTION (PAYMENT_ID)
);

CREATE TABLE TRSYDEMO.BANK_RECON_STAGE
(
    FILE_ID            CHAR(12)       NOT NULL,
    SEQUENCE_NO        INTEGER        NOT NULL,
    PAYMENT_ID         CHAR(12)       NOT NULL,
    BANK_TRACE         CHAR(15)       NOT NULL,
    OUTCOME            CHAR(1)        NOT NULL,
    AMOUNT             DECIMAL(13,2)  NOT NULL,
    CURRENCY           CHAR(3)        NOT NULL,
    REASON_CODE        CHAR(4)        NOT NULL,
    SETTLEMENT_DATE    DATE           NOT NULL,
    PRIMARY KEY (FILE_ID, SEQUENCE_NO)
);

CREATE TABLE TRSYDEMO.RECON_EVENT
(
    BANK_TRACE         CHAR(15)       NOT NULL,
    FILE_ID            CHAR(12)       NOT NULL,
    PAYMENT_ID         CHAR(12)       NOT NULL,
    OUTCOME            CHAR(1)        NOT NULL,
    AMOUNT             DECIMAL(13,2)  NOT NULL,
    CURRENCY           CHAR(3)        NOT NULL,
    REASON_CODE        CHAR(4)        NOT NULL,
    SETTLEMENT_DATE    DATE           NOT NULL,
    CREATED_TS         TIMESTAMP      NOT NULL WITH DEFAULT,
    PRIMARY KEY (BANK_TRACE)
);

CREATE TABLE TRSYDEMO.RECON_EXCEPTION
(
    EXCEPTION_ID       BIGINT GENERATED ALWAYS AS IDENTITY,
    FILE_ID            CHAR(12)       NOT NULL,
    PAYMENT_ID         CHAR(12),
    BANK_TRACE         CHAR(15),
    EXCEPTION_CODE     CHAR(2)        NOT NULL,
    EXPECTED_AMOUNT    DECIMAL(13,2),
    ACTUAL_AMOUNT      DECIMAL(13,2),
    STATUS             CHAR(1)        NOT NULL WITH DEFAULT 'O',
    CREATED_TS         TIMESTAMP      NOT NULL WITH DEFAULT,
    PRIMARY KEY (EXCEPTION_ID)
);
