CREATE TABLE BANKDEMO.CUSTOMER
(
    CUSTOMER_ID    CHAR(10)      NOT NULL,
    CUSTOMER_NAME  VARCHAR(60)   NOT NULL,
    STATUS         CHAR(1)       NOT NULL WITH DEFAULT 'A',
    CREATED_TS     TIMESTAMP     NOT NULL WITH DEFAULT,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE BANKDEMO.ACCOUNT
(
    ACCOUNT_ID      CHAR(10)       NOT NULL,
    CUSTOMER_ID     CHAR(10)       NOT NULL,
    ACCOUNT_TYPE    CHAR(3)        NOT NULL,
    STATUS          CHAR(1)        NOT NULL WITH DEFAULT 'A',
    BALANCE         DECIMAL(11,2)  NOT NULL WITH DEFAULT 0,
    OVERDRAFT_LIMIT DECIMAL(9,2)   NOT NULL WITH DEFAULT 0,
    LAST_TXN_DATE   DATE,
    UPDATED_TS      TIMESTAMP      NOT NULL WITH DEFAULT,
    PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT BANKDEMO.FK_ACCOUNT_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES BANKDEMO.CUSTOMER (CUSTOMER_ID),
    CONSTRAINT BANKDEMO.CK_ACCOUNT_TYPE
        CHECK (ACCOUNT_TYPE IN ('CHK', 'SAV')),
    CONSTRAINT BANKDEMO.CK_ACCOUNT_STATUS
        CHECK (STATUS IN ('A', 'H', 'C'))
);

CREATE TABLE BANKDEMO.ACCOUNT_TXN
(
    TXN_ID          CHAR(10)       NOT NULL,
    ACCOUNT_ID      CHAR(10)       NOT NULL,
    TXN_DATE        DATE           NOT NULL,
    TXN_TYPE        CHAR(1)        NOT NULL,
    AMOUNT          DECIMAL(11,2)  NOT NULL,
    FEE_AMOUNT      DECIMAL(9,2)   NOT NULL WITH DEFAULT 0,
    BALANCE_AFTER   DECIMAL(11,2)  NOT NULL,
    SOURCE_REF      CHAR(13)       NOT NULL,
    POSTED_TS       TIMESTAMP      NOT NULL WITH DEFAULT,
    PRIMARY KEY (TXN_ID),
    CONSTRAINT BANKDEMO.FK_TXN_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID)
        REFERENCES BANKDEMO.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT BANKDEMO.CK_TXN_TYPE
        CHECK (TXN_TYPE IN ('C', 'D'))
);

CREATE INDEX BANKDEMO.IX_TXN_ACCOUNT_DATE
    ON BANKDEMO.ACCOUNT_TXN (ACCOUNT_ID, TXN_DATE, TXN_ID);
